export enum MuscleType {
  CHEST = 'CHEST',
  BACK = 'BACK',
  BICEPS = 'BICEPS',
  TRICEPS = 'TRICEPS',
  SHOULDERS = 'SHOULDERS',
  LEGS = 'LEGS',
  CALVES = 'CALVES',
  ABS = 'ABS',
  FULL_BODY = 'FULL_BODY',
  GLUTES = 'GLUTES',
  HAMSTRINGS = 'HAMSTRINGS',
  QUADRICEPS = 'QUADRICEPS',
  ADDUCTORS_ABDUCTORS = 'ADDUCTORS_ABDUCTORS',
}

export enum ExecutionType {
  REPETITION = 'REPETITION',
  TIME = 'TIME',
}
